### ISSUE TITLE
Use submodule for laradock

### ISSUE THREAD

**Issue by thatnerdjosh** [bagart/laradock_env#1]
Would it make sense to use a submodule/symlink to pull the laradock source instead of maintaining two source trees and merging? If so, I could work on that and make a PR :)

Cool project btw, makes it where I don't need to copy and paste the directory for different envs 👍

**Comment by bagart** [comment]
I think, work env must place in repo. Laradock is work like submodule(before this project I use it like sublodule) but it's not private env. and it's not stable.  any update can crush old config. 
symlink is possible but not flexible(windows)
I create this project it before .env in Laradock. I think next step is include different env files by variable
thanks for feedback

**Comment by bagart** [comment]
Version2 is released
